name: CI on Push and Pull Request

on: [push, pull_request]

jobs:        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
    - name: Install dependencies
      run: nuget restore SimplePomodoro.sln
    - name: Build
      run: msbuild SimplePomodoro/SimplePomodoro.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
